# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch:
  push:
    branches: [ "develop", "release/*" ]
  
  workflow_run:
    workflows:
      - "Java CI with Maven"
    types: 
      - completed
    
jobs:
  maven:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v3

    - name: setup
      run: . .github/scripts/setup

    - name: checkout scripts
      run: git clone https://github.com/conxult/eval-script.git scripts

    - name: run script
      run: echo scripts/bin/do-something.sh

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: mvn version
      run: |
        mvn versions:set -DnewVersion=$VERSION
        cd base && mvn versions:set -DnewVersion=$VERSION

#    - name: mvn package
#      run: mvn -B package

    - name: mvn clean install
      env:
        GITHUB_USERNAME: x-access-token
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run:
        mvn --settings settings.xml clean install
        
