# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/senv | sortetup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

env:
  PROJECT_NAME: "cx-eval-base"
  VERSION_BASE: "1.0"

on:
  workflow_dispatch:
  push:
    branches: [ "develop", "release/*", "task/*", "feature/*", "bugfix/*" ]
  
  workflow_run:
    workflows:
      - "Java CI with Maven"
    types: 
      - completed
    
jobs:
  maven:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: setup java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        cache: 'maven'

#    - name: checkout scripts
#      run: |
#        git clone https://github.com/conxult/eval-script.git scripts
#        find scripts
#        echo scripts/bin/do-something.sh

    - name: set version
      run: |
        . .github/scripts/setup
        setVersion

    - name: mvn versions:set
      run: |
        . .github/scripts/setup
        mavenSetVersions

    - name: mvn clean install package
      run: |
        echo mvn --batch-mode clean install
        echo pom.xml:
        cat pom.xml
        echo base/pom.xml:
        cat base/pom.xml
        mvn -B clean install package
        
    - name: mvn deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      run: |
        echo . .github/scripts/setup
        echo mavenDeploy
        mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        

