# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch:
  push:
    branches: [ "develop", "release/*" ]
  
  workflow_run:
    workflows:
      - "Java CI with Maven"
    types: 
      - completed
    
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: setup
      run: . .github/scripts/setup
      
    - name: mvn vwrsion
      run: mvn versions:set -DnewVersion=$VERSION

    - name: mvn clean install
      run: mvn clean install

    - name: checkout scripts
      run: git clone https://github.com/conxult/eval-script.git 

    - name: run script
      run: echo eval-script/bin/do-something.sh
      
    - name: prepare publish
      run: mkdir upload && cp base/target/*.jar upload

    - name: check upload
      run: find upload
      
#   - name: publish to github
#      uses: actions/upload-artifact@v1
#      with:
#        name: Package
#        path: upload

    - name: deploy to github
      run: ls -al && cat settings.xml && mvn -s settings.xml --batch-mode deploy
      env:
        GITHUB_ACTOR: conxult
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
