# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch:
  push:
    branches: [ "develop", "release/*" ]
  
  workflow_run:
    workflows:
      - "Java CI with Maven"
    types: 
      - completed
    
jobs:
  maven:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: setup
      run: . .github/scripts/setup

    - name: checkout scripts
      run: git clone https://github.com/conxult/eval-script.git scripts

    - name: run script
      run: echo scripts/bin/do-something.sh

    - name: setup java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: mvn version
      run: |
        mvn versions:set -DnewVersion=$VERSION
        cd base && mvn versions:set -DnewVersion=$VERSION

    - name: mvn deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      run: cd base && mvn --batch-mode deploy

    - name: cat ~/.m2/settings.xml
      run: cat ~/.m2/settings.xml

#    - name: mvn package
#      run: mvn -B package
