# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/senv | sortetup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

env:
  PROJECT_NAME: "cx-eval-base"
  VERSION_BASE: "1.0"

on:
  workflow_dispatch:
  push:
    branches: [ "develop", "release/*", "task/*", "feature/*", "bugfix/*" ]
  
  workflow_run:
    workflows:
      - "Java CI with Maven"
    types: 
      - completed
    
jobs:
  setup:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip-ci]') }}
    permissions:
      contents: read
      packages: write

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: setup java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        cache: 'maven'

    - name: show information
      run: |
        find .

  maven:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:

#    - name: checkout scripts
#      run: |
#        git clone https://github.com/conxult/eval-script.git scripts
#        find scripts
#        echo scripts/bin/do-something.sh

    - name: versioning
      run: |
        . scripts/versioning

    - name: maven versions build deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      run: |
        mvn -B versions:set -DnewVersion=$VERSION
        mvn -B clean install deploy -s $GITHUB_WORKSPACE/settings.xml        
        echo mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        

