# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ "develop", "release/*" ]
  workflow_run:
    workflows:
      - "Java CI with Maven"
    types: 
      - completed
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Show environment
      run: env

  publish:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - name: Publish to GitHub Packages Apache Maven
    - run: mkdir upload && cp target/*.jar upload
    - uses: actions/upload-artifact@v1
      with:
        name: Package
        path: upload
